const ITEMLIST = [
  {
    id: 1,
    name: "Cây Cam Ngọt Của Tôi",
    price: "75.000 đ",
    discount: "-31%",
    reviews: 4.9,
    numberOfSale: "Đã bán 1000",
    image: require("../../assets/images/chrome-capture-2022-10-21.png"),
  },
  {
    id: 2,
    name: "Một Thoáng Ta Rực Rỡ Ở Nhân Gian",
    price: "96.300 đ",
    discount: "-29%",
    reviews: 4.8,
    numberOfSale: "Đã bán 1000",
    image: require("../../assets/images/1thoangonhangian.png"),
  },
  {
    id: 3,
    name: "Án Mạng Trên Sông Nile",
    price: "94.300 đ",
    discount: "-30%",
    reviews: 4.7,
    numberOfSale: "Đã bán 1000",
    image: require("../../assets/images/anmangtrensongnile.png"),
  },
  {
    id: 4,
    name: "Mã 612: Ai Đã Giết Hoàng Tử Bé",
    price: "91.700 đ",
    discount: "-27%",
    reviews: 4.9,
    numberOfSale: "Đã bán 1000",
    image: require("../../assets/images/aidagiethoangtube.png"),
  },
  {
    id: 5,
    name: "Mã 612: Ai Đã Giết Hoàng Tử Bé",
    price: "91.700 đ",
    discount: "-27%",
    reviews: 4.9,
    numberOfSale: "Đã bán 1000",
    image: require("../../assets/images/aidagiethoangtube.png"),
  },
  {
    id: 6,
    name: "Mã 612: Ai Đã Giết Hoàng Tử Bé",
    price: "91.700 đ",
    discount: "-27%",
    reviews: 4.9,
    numberOfSale: "Đã bán 1000",
    image: require("../../assets/images/aidagiethoangtube.png"),
  },
  {
    id: 7,
    name: "Mã 612: Ai Đã Giết Hoàng Tử Bé",
    price: "91.700 đ",
    discount: "-27%",
    reviews: 4.9,
    numberOfSale: "Đã bán 1000",
    image: require("../../assets/images/aidagiethoangtube.png"),
  },
  {
    id: 8,
    name: "Mã 612: Ai Đã Giết Hoàng Tử Bé",
    price: "91.700 đ",
    discount: "-27%",
    reviews: 4.9,
    numberOfSale: "Đã bán 1000",
    image: require("../../assets/images/aidagiethoangtube.png"),
  },
  {
    id: 9,
    name: "Mã 612: Ai Đã Giết Hoàng Tử Bé",
    price: "91.700 đ",
    discount: "-27%",
    reviews: 4.9,
    numberOfSale: "Đã bán 1000",
    image: require("../../assets/images/aidagiethoangtube.png"),
  },
];
export default ITEMLIST;
